export const styles = {
  screen: {
    background:  "#0a0a0a",
    minHeight:   "100vh",
    color:       "#f0f0f0",
    fontFamily:  "'Helvetica Neue', Helvetica, Arial, sans-serif",
    maxWidth:    430,
    margin:      "0 auto",
    position:    "relative",
    paddingBottom: 40,
  },
  header: {
    display:         "flex",
    justifyContent:  "space-between",
    alignItems:      "center",
    padding:         "20px 16px 12px",
    position:        "sticky",
    top:             0,
    background:      "#0a0a0a",
    zIndex:          10,
    borderBottom:    "1px solid #1a1a1a",
  },
  headerTitle: { fontSize: 22, fontWeight: 800, letterSpacing: -0.5 },
  headerSub:   { fontSize: 12, color: "#666", marginTop: 1 },
  iconBtn: {
    background:  "#1a1a1a",
    border:      "none",
    color:       "#fff",
    width:       36,
    height:      36,
    borderRadius: 10,
    fontSize:    20,
    cursor:      "pointer",
    display:     "flex",
    alignItems:  "center",
    justifyContent: "center",
  },
  filterBar: {
    display:       "flex",
    gap:           4,
    overflowX:     "auto",
    padding:       "10px 12px",
    scrollbarWidth: "none",
    borderBottom:  "1px solid #111",
  },
  grid: {
    display:             "grid",
    gridTemplateColumns: "1fr 1fr",
    gap:                 12,
    padding:             "14px 12px",
  },
  card: {
    background:   "#141414",
    borderRadius: 12,
    overflow:     "hidden",
    cursor:       "pointer",
    transition:   "transform 0.1s",
  },
  cardImg: {
    width:    "100%",
    height:   130,
    background: "#1e1e1e",
    position: "relative",
    overflow: "hidden",
  },
  imgPlaceholder: {
    width:          "100%",
    height:         "100%",
    display:        "flex",
    alignItems:     "center",
    justifyContent: "center",
    background:     "#1e1e1e",
  },
  cardBody:   { padding: "8px 10px 10px" },
  cardName:   { fontSize: 13, fontWeight: 700, lineHeight: 1.3, marginBottom: 2 },
  cardMeta:   { fontSize: 11, color: "#888" },
  cardLoc:    { fontSize: 11, color: "#555", marginTop: 2 },
  claimedOverlay: {
    position:   "absolute",
    bottom: 0, left: 0, right: 0,
    background: "rgba(0,0,0,0.7)",
    color:      "#ff9500",
    fontSize:   11,
    fontWeight: 700,
    textAlign:  "center",
    padding:    "4px 0",
  },
  expiryBadge: {
    padding:      "2px 7px",
    borderRadius: 8,
    color:        "#fff",
    fontSize:     11,
    fontWeight:   700,
  },
  detailHeader: {
    display:        "flex",
    justifyContent: "space-between",
    alignItems:     "center",
    padding:        "16px 16px 12px",
    borderBottom:   "1px solid #1a1a1a",
    position:       "sticky",
    top:            0,
    background:     "#0a0a0a",
    zIndex:         10,
  },
  backBtn: {
    background: "none",
    border:     "none",
    color:      "#007aff",
    fontSize:   15,
    cursor:     "pointer",
    padding:    "4px 0",
  },
  detailImg:  { width: "100%", height: 240, background: "#1a1a1a", overflow: "hidden" },
  detailBody: { padding: "16px 16px 32px" },
  detailName: { fontSize: 22, fontWeight: 800, margin: 0, letterSpacing: -0.5 },
  detailDesc: { fontSize: 14, color: "#888", marginTop: 6, marginBottom: 12 },
  detailMeta: { marginBottom: 16 },
  claimedBanner: {
    background: "#1a1200",
    border:     "1px solid #ff9500",
    borderRadius: 10,
    padding:    "10px 14px",
    fontSize:   14,
    color:      "#ff9500",
    display:    "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  unclaimBtn: {
    background:   "none",
    border:       "1px solid #ff9500",
    color:        "#ff9500",
    borderRadius: 6,
    padding:      "4px 10px",
    fontSize:     12,
    cursor:       "pointer",
  },
  claimBtn: {
    width:        "100%",
    padding:      "14px 0",
    background:   "#007aff",
    color:        "#fff",
    border:       "none",
    borderRadius: 12,
    fontSize:     16,
    fontWeight:   700,
    cursor:       "pointer",
    marginTop:    8,
  },
  addForm: { padding: "8px 16px 40px" },
  imgUploadBox: {
    width:        "100%",
    height:       180,
    background:   "#1a1a1a",
    borderRadius: 12,
    border:       "2px dashed #333",
    display:      "flex",
    alignItems:   "center",
    justifyContent: "center",
    cursor:       "pointer",
    overflow:     "hidden",
    marginBottom: 4,
  },
  input: {
    width:        "100%",
    background:   "#1a1a1a",
    border:       "1px solid #2a2a2a",
    borderRadius: 10,
    color:        "#f0f0f0",
    fontSize:     15,
    padding:      "11px 12px",
    boxSizing:    "border-box",
    outline:      "none",
    appearance:   "none",
  },
  dropdown: {
    position:     "absolute",
    top:          "100%",
    left:         0,
    right:        0,
    background:   "#1e1e1e",
    border:       "1px solid #333",
    borderRadius: 10,
    zIndex:       20,
    overflow:     "hidden",
    maxHeight:    180,
    overflowY:    "auto",
  },
  dropItem: {
    padding:      "10px 14px",
    fontSize:     14,
    cursor:       "pointer",
    borderBottom: "1px solid #2a2a2a",
    color:        "#eee",
  },
  btnPrimary: {
    background:   "#007aff",
    color:        "#fff",
    border:       "none",
    borderRadius: 10,
    padding:      "10px 20px",
    fontSize:     14,
    fontWeight:   700,
    cursor:       "pointer",
    flex:         1,
  },
  btnSecondary: {
    background:   "#2a2a2a",
    color:        "#fff",
    border:       "none",
    borderRadius: 10,
    padding:      "10px 20px",
    fontSize:     14,
    cursor:       "pointer",
    flex:         1,
  },
  btnDanger: {
    background:   "none",
    border:       "1px solid #ff3b30",
    color:        "#ff3b30",
    borderRadius: 10,
    padding:      "10px 20px",
    fontSize:     14,
    cursor:       "pointer",
    flex:         1,
  },
  modal: {
    position:       "fixed",
    inset:          0,
    background:     "rgba(0,0,0,0.7)",
    zIndex:         100,
    display:        "flex",
    alignItems:     "flex-end",
    justifyContent: "center",
  },
  modalBox: {
    background:   "#1a1a1a",
    borderRadius: "16px 16px 0 0",
    padding:      "24px 20px 40px",
    width:        "100%",
    maxWidth:     430,
  },
  empty: {
    gridColumn: "span 2",
    textAlign:  "center",
    color:      "#444",
    padding:    "60px 20px",
    fontSize:   15,
    lineHeight: 1.8,
  },
  spinner: {
    display:        "flex",
    alignItems:     "center",
    justifyContent: "center",
    height:         "100vh",
    fontSize:       28,
    color:          "#333",
  },
};
